version: '3.8'

services:
    blockchain:
        image: blockchain-be
        build:
            context: .
        ports:
            - ${APP_PORT}:3000
        environment:
            DATABASE_HOST: postgres
            DATABASE_PORT: 5432
            DATABASE_USER: ${DATABASE_USER}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_NAME: ${DATABASE_NAME}
            REDIS_HOST: redis
            REDIS_PORT: 6379
        networks:
            - blockchain-network

    redis:
        image: redis:5
        ports:
            - ${REDIS_PORT}:6379
        networks:
            - blockchain-network

    postgres:
        image: postgres:11
        volumes:
            - blockchain-volume:/data/db
        ports:
            - ${DATABASE_PORT}:5432
        environment:
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_DB: ${DATABASE_NAME}
        networks:
            - blockchain-network

networks:
    blockchain-network:
volumes:
    blockchain-volume:
