version: '3.8'

services:
    redis:
        image: redis:5
        ports:
            - ${REDIS_PORT}:6379
        networks:
            - blockchain-network

    postgres:
        image: postgres:11
        volumes:
            - blockchain-volume:/data/db
        ports:
            - ${DATABASE_PORT}:5432
        environment:
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_DB: ${DATABASE_NAME}
        networks:
            - blockchain-network

networks:
    blockchain-network:
volumes:
    blockchain-volume:
